### ISSUE TITLE
Will this work in Sitefinity 3.6?

### ISSUE THREAD

**Issue by upekshapriya** [alanta/sitefinity-url-fixes#1]
We have an old installation of Sitefinity 3.6 which is redirecting to a 404 page but returning a 302 error. Will this be able to fix it?

**Comment by alanta** [comment]
That is exactly one of the problems it aims to resolve. But, it's been a while and I don't recall exactly if 3.6 and 3.7 are compatible in this area, though I seem to recall that they are.

This is pretty much a drop-in peace of code, so you can give it a try. If it doesn't work, just revert the changes to web.config and delete the code file and the site is back to normal.
